export const popularBusDestinations = [
  {
    id: "vung-tau",
    title: "Vé Xe Đi Vũng Tàu",
    slug: "vung-tau",
    destination: "Vũng Tàu",
    image: "/assets/hotels/vungtau-1.jpg",
    href: "/bus/destination/vung-tau",
  },
  {
    id: "da-lat",
    title: "Vé Xe Đi Đà Lạt",
    slug: "da-lat",
    destination: "Đà Lạt",
    image: "/assets/destinations/dalat.jpg",
    href: "/bus/destination/da-lat",
  },
  {
    id: "nha-trang",
    title: "Vé Xe Đi Nha Trang",
    slug: "nha-trang",
    destination: "Nha Trang",
    image: "/assets/destinations/nhatrang.jpg",
    href: "/bus/destination/nha-trang",
  },
  {
    id: "phan-thiet",
    title: "Vé Xe Đi Phan Thiết",
    slug: "phan-thiet",
    destination: "Phan Thiết",
    image: "/assets/hotels/phanthiet-1.jpg",
    href: "/bus/destination/phan-thiet",
  },
  {
    id: "sai-gon",
    title: "Vé Xe Đi Sài Gòn",
    slug: "sai-gon",
    destination: "Sài Gòn",
    image: "/assets/destinations/hcm.jpeg",
    href: "/bus/destination/sai-gon",
  },
  {
    id: "da-nang",
    title: "Vé Xe Đi Đà Nẵng",
    slug: "da-nang",
    destination: "Đà Nẵng",
    image: "/assets/destinations/danang.jpg",
    href: "/bus/destination/da-nang",
  },
];
